#: Fonts 

font_family      JetBrainsMono Nerd Font
font_size 11.0

# -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-

#: CURSOR SETTINGS
cursor_shape beam
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-

#: SCROLLBAR

scrollbar hovered
scrollbar_width 0.4
scrollbar_hover_width 0.4

# -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-

# Window layout

remember_window_size no
initial_window_width 1200
initial_window_height 680

window_border_width 2px
draw_minimal_borders yes
draw_window_borders_for_single_window yes
window_margin_width 4
single_window_margin_width 4
window_padding_width 4
single_window_padding_width 5
placement_strategy center
hide_window_decorations yes
confirm_os_window_close -1

tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 1
tab_activity_symbol *
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title} ({num_windows})"
active_tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"

# KeyMaps
map kitty_mod ctrl+shift
map kitty_mod+t new_tab_with_cwd
map kitty_mod+n launch --cwd=current --type=os-window
map kitty_mod+enter new_window_with_cwd

map ctrl+alt+t goto_layout tall
map ctrl+alt+s goto_layout split
map ctrl+alt+S goto_layout stack
map ctrl+alt+g goto_layout grid

copy_on_select yes

background_opacity 0.8
background_blur 1

# BEGIN_KITTY_THEME
# Eldritch
include current-theme.conf
# END_KITTY_THEME
