[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "natural"
sort_dir_first = true
sort_translit  = true
scrolloff      = 5
mouse_events   = [ "click", "scroll", "move", "touch" ]
title_format   = "Yazi: {cwd}"

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 600
max_height      = 900

[opener]
edit = [
	{ run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
	{ run = 'ya pub extract --list %*',   desc = "Extract here", for = "windows" },
]
play = [
  { run = 'DRI_PRIME=1 mpv --hwdec=nvdec --force-window=yes "$@"', desc = "mpv NVIDIA", orphan = true, for = "unix" },
  { run = 'mpv --hwdec=auto --force-window=yes "$@"', desc = "mpv iGPU", orphan = true, for = "unix" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

[tasks]
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]

[plugin]
prepend_fetchers = [
	# Mimetype
	{ id = "mime", name = "*", run = "mime", prio = "high" },
  { id = "git", name = "*", run = "git"},
  { id = "git", name = "*/", run = "git"},
]

[input]
cursor_blink = false
