#!/usr/bin/sh

sxhkd &
feh --bg-fill $HOME/.dotfiles/Pictures/star-wars-ascii.jpg &
polybar &
picom --config $HOME/.dotfiles/picom/picom.conf &
dunst &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width    3
bspc config window_gap      6

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
