########################
### HYPR KEYBINDINGS ###
########################

source = ~/.config/hypr/programs.conf

$mainMod = ALT

bind = SUPER, RETURN, exec, $terminal
bind = SUPER, E, exec, $fileManager
bind = SUPER SHIFT, E, exec, $fileManager_tty
bind = SUPER, B, exec, $browser
bind = SUPER SHIFT, B, exec, $browser_private
bind = SUPER, D, exec, $menu
bind = SUPER, M, exec, $mail
bind = SUPER, P, exec, spotify-launcher

# close & kill
bind = $mainMod, Q, killactive,
bind = $mainMod SHIFT, Q, forcekillactive,

# logout hyprland
bind = $mainMod SUPER, Q, exit,

# Shut down & restart
bind = SUPER, Q, exec, systemctl poweroff
bind = SUPER SHIFT, Q, exec, systemctl reboot
bind = ,XF86PowerOff, exec, systemctl suspend

# tiling modes
bind = $mainMod, SPACE, togglefloating,
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, F, fullscreen , 1
bind = $mainMod SHIFT, F, fullscreen , 0

# Move window focus with mainMod + WASD
bind = $mainMod, A, movefocus, l
bind = $mainMod, D, movefocus, r
bind = $mainMod, W, movefocus, u
bind = $mainMod, S, movefocus, d

# Move window with mainMod + shift + WASD
bind = $mainMod SHIFT, A, movewindow, l
bind = $mainMod SHIFT, D, movewindow, r
bind = $mainMod SHIFT, W, movewindow, u
bind = $mainMod SHIFT, S, movewindow, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mainMod, MINUS, togglespecialworkspace, magic
bind = $mainMod SHIFT, MINUS, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Move windows with mainMod + HJKL
binde = $mainMod, H, moveactive, -40 0
binde = $mainMod, J, moveactive, 0 40
binde = $mainMod, K, moveactive, 0 -40
binde = $mainMod, L, moveactive, 40 0

# Resize windows outward with mainMod + shift + HJKL
binde = $mainMod SHIFT, H, resizeactive, -40 0
binde = $mainMod SHIFT, J, resizeactive, 0 40
binde = $mainMod SHIFT, K, resizeactive, 0 -40
binde = $mainMod SHIFT, L, resizeactive, 40 0

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, ~/.dotfiles/hypr/mic-toggle.sh
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

bindl = ,XF86TouchpadToggle, exec, ~/.dotfiles/hypr/touchpad-toggle.sh

bind = ,Print, exec, grim && notify-send grim 'Screenshot taken'
# bind = ALT ,Print, exec, flameshot gui -p ~/Pictures/Screenshot

bind = ,XF86PowerOff, exec, power.sh
