preload = /home/acausr/.dotfiles/Pictures/od_leaf-colorized.png
preload = /home/acausr/.dotfiles/Pictures/1.png
preload = /home/acausr/.dotfiles/Pictures/powerline-landscape.jpg
wallpaper =, /home/acausr/.dotfiles/Pictures/od_leaf-colorized.png
