preload = /home/acausr/.dotfiles/Pictures/divine-child-of-rejuvenating-waters.png
preload = /home/acausr/.dotfiles/Pictures/whale-in-space.png
preload = /home/acausr/.dotfiles/Pictures/black_hole.jpg
wallpaper =, /home/acausr/.dotfiles/Pictures/black_hole.jpg
