general = {
    ignore_empty_input = true
    fail_timout = 1000
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = /home/acausr/Pictures/Pictures/Wallpapers/wirefeather.png
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgb(0, 0, 0)
    check_color = rgb(0, 0, 0)
    fail_color = rgb(ff6633)
    # #000
    font_color = rgb(0, 0, 0)
    fade_on_empty = false
    rounding = 0

    font_family = JetBrainsMono Nerd Font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    dots_text_format = *
    dots_size = 0.4
    dots_spacing = 0.3


    position = 50, 80
    halign = left
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = Bitcount Prop Single
    color = rgb(0, 0, 0)

    position = -30, -20
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 30
    font_family = Bitcount Prop Single
    color = rgb(0, 0, 0)

    position = -30, -150
    halign = right
    valign = top
}

# label {
#     monitor = eDP-1
#     text = $LAYOUT[en,ru]
#     font_size = 24
#     onclick = hyprctl switchxkblayout all next
#
#     position = 250, -20
#     halign = center
#     valign = center
# }
