preload = /home/acausr/.dotfiles/Pictures/anime-girl-purple-eyes.png
preload = /home/acausr/.dotfiles/Pictures/Dawn_over_mountain.png
wallpaper =, /home/acausr/.dotfiles/Pictures/anime-girl-purple-eyes.png
