plugin {
  hyprspace {
    gesture = 3, up, dispatcher, overview:toggle
  }
  hyprexpo {
    columns = 5
    gap_size = 5
    bg_col = rgb(111111)
    workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1
    skip_empty = true

    gesture_distance = 300 # how far is the "max" for the gesture
    #
    # enable_gesture = true
    # gesture_fingers = 3
    # gesture_distance = 300
    # gesture_positive = true  # swipe down to enable expo
  }
}
