###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$fileManager_tty = yazi
$browser = firefox
$browser_private = librewolf
$mail = thunderbird
$menu = ~/.dotfiles/rofi/Launcher/launcher.sh
$powermenu = ~/.dotfiles/rofi/PowerMenu/powermenu.sh
