windowrule = float, class:^(Spotify)$
windowrule = center, class:^(Spotify)$
#######################
# Floating Apps
#######################
windowrule = float, title:^(Calculator)$
windowrule = float, initialTitle:^(Friends List)$
windowrule = float, title:^(VirtualBox)$
