# windowrule = float, class:^(Spotify)$
# windowrule = center, class:^(Spotify)$
# #######################
# # Floating Apps
# #######################
# windowrule = float, initialTitle:^(Friends List)$
windowrule {
  name = apply-float
  match:class = ^Spotify$
  match:title = ^Calculator$

  float = on
}
