set -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

#---------------------------------
#--------STATUS LINE--------------
#---------------------------------

set -g status-style bg=#40444e
set -g status-left "#[fg=color235,bg=white] 󰄶 #S#[fg=white,bg=#40444e] "
set -g status-right '#[fg=color1]#(~/.dotfiles/tmux/battery.sh)% #[fg=color1]#[fg=color235,bg=color1,bold] %b %d %H:%M '
set -g window-status-format "#I > #W"
set -g window-status-current-style fg=green
set -g window-status-last-style fg=color1
set -g window-status-separator "  " 

# prefix key
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# split binds
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
