export BROWSER="librewolf"
export FILE_MANAGER="nautilus"
export TUI_FILE_MANAGER="yazi"
export TERMINAL="kitty"
export DOT_DIR="$HOME/.dotfiles"
export DOT_PIC_DIR="$DOT_DIR/Pictures"
export WALLPAPER="$DOT_PIC_DIR/star-wars-ascii.jpg"
export LM_LICENSE_FILE=/home/acausr/opt/intel/LR-245010_License.dat
