export ZSH="$HOME/.oh-my-zsh"

# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
# DISABLE_MAGIC_FUNCTIONS="true"
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"
# HIST_STAMPS="mm/dd/yyyy"
# ZSH_CUSTOM=/path/to/new-custom-folder

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# =========================================
# Key Bindings
# =========================================
bindkey -v  # enable vi mode


# =========================================
# STARSHIP PROMPT
# =========================================
eval "$(starship init zsh)"

# Fix Starship zle-keymap-select recursion bug
function starship_vi_mode_fix() {
  if [[ -z "$_zle_guard" ]]; then
    _zle_guard=1
    { starship_precmd &>/dev/null }
    zle reset-prompt
    unset _zle_guard
  fi
}
zle -N zle-keymap-select starship_vi_mode_fix

# =========================================
# sourcing all custom config files
# =========================================
for file in ~/.dotfiles/zsh/shell_config/*; do
    source $file
done
