export PATH="$HOME/.local/bin:$PATH"

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set the name of the theme to load
# Set to "random" to load random theme
ZSH_THEME="agnoster"
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"

# HIST_STAMPS="mm/dd/yyyy"

# ZSH_CUSTOM=/path/to/new-custom-folder

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=(git autoupdate zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh
source $HOME/.dotfiles/sys_vars.sh

# ===========================================
# USER CONFIGURATION
# ===========================================

# export MANPATH="/usr/local/man:$MANPATH"

# manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# ----------------------------------------
# Key bindings
#
bindkey -v  # enable vi mode
bindkey '^H' backward-kill-word


# =========================================
# STARSHIP PROMPT
# =========================================
eval "$(starship init zsh)"

# Fix Starship zle-keymap-select recursion bug
function starship_vi_mode_fix() {
  if [[ -z "$_zle_guard" ]]; then
    _zle_guard=1
    { starship_precmd &>/dev/null }
    zle reset-prompt
    unset _zle_guard
  fi
}
zle -N zle-keymap-select starship_vi_mode_fix

# =========================================
# sourcing all custom config files
# =========================================
for file in ~/.dotfiles/zsh/shell_config/*; do
    source $file
done

# on startup
clear
